spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product-order-payment
    username: root
    password: Vikas/1998@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


server:
  port: 8082